# Generated by Django 5.2.8 on 2026-03-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_openresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='openresponse',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
